### ISSUE TITLE
Replace `source-map` with `@jridgewell/trace-mapping`

### ISSUE THREAD

**Issue by SimenB** [istanbuljs/v8-to-istanbul#185]
According to its benchmarks, it's way quicker, and it doesn't require us to use async code. Main motivation however, is that 0.7 of `source-map` is completely broken on the upcoming node v18: https://github.com/nodejs/node/issues/42638

I tried a quick migration, but `v8-to-istanbul` uses `consumer.generatedPositionFor`, which doesn't exist in `@jridgewell/trace-mapping`.

/cc @jridgewell

**Comment by SimenB** [comment]
If it can be done in a better way, that's of course preferable 😀

**Comment by jridgewell** [comment]
Turns out there's not a faster algorithm that we can do. I misunderstood the API you were trying to implement, and in order to find the start of the next segment _in source order_, you need to use `generatedPositionFor`. It's now [implemented](https://github.com/jridgewell/trace-mapping/pull/1). I'll do a release later today or Mon

**Comment by SimenB** [comment]
Sweet, thanks!

**Comment by SimenB** [comment]
FWIW, by quick and dirty port: https://github.com/istanbuljs/v8-to-istanbul/tree/trace-mapping

Not tested with the new `generatedPositionFor` method, just made assumptions it's present
