### ISSUE TITLE
source maps do no respect sourceRoot 

### ISSUE THREAD

**Issue by Toxicable** [istanbuljs/v8-to-istanbul#31]
Under the build tool I am using .ts files do not live next to .js files, therefore we use sourceRoot to point the source maps at the correct source dir.

This  line here:  https://github.com/istanbuljs/v8-to-istanbul/blob/master/lib/v8-to-istanbul.js#L40
```
this.path = relativeTo(rawSourceMap.sourcemap.sources[0], this.path)
```
fails to resolve that logic, we've had to modify it to be
```
this.path = join(rawSourceMap.sourcemap.sourceRoot, rawSourceMap.sourcemap.sources[0])
```
for it to be able to resolve sourceRoot's correctly

**Comment by bcoe** [comment]
@Toxicable what is `sourceRoot` by default? wondering if we're safe to always use the logic you shared above, or whether we should make it conditional on the value of `sourceRoot` being set?

**Comment by bcoe** [comment]
will happily take a patch for this :smile:

**Comment by Toxicable** [comment]
@bcoe usually it's empty string by default.
Will look at how we can combine that logic, but otherwise a conditional should work fine.
I just want to make sure the changes here actually conform to how source maps are meant to be read

**Comment by bcoe** [comment]
we need to also make sure that relative paths populated in `sourceRoot` take into account `process.cwd()` when determining the final path, see: https://github.com/istanbuljs/v8-to-istanbul/pull/39

To add an additional pain point, it seems that some sourceMap instrumenters sometimes add the filename in `sourceRoot`, so we need to be mindful to strip this out when determining the relative path.

I think for a path forward:

* `lib/pathutils.js` should be updated to handle these edge-cases, rather than using `join` directly (as is currently the case).
* the c8 test suite should be run with the updated version of `v8-to-istanbul` before releasing it.

**Comment by bcoe** [comment]
@Toxicable mind checking if this is fixed in the latest release? I did some reworking around how we handled path resolution, in an effort to make it closer to Source Map V3.

**Comment by Toxicable** [comment]
Whops, sorry for not checking back in here sooner.
Looks like it handles sourceRoot fine now, thanks!
