### ISSUE TITLE
fn.count always zero?

### ISSUE THREAD

**Issue by chriscapaci** [istanbuljs/v8-to-istanbul#7]
I'm seeing coverage files where my function coverage is always 0/n for every file. My coverage files have the functions in them with the names and line numbers, etc. However, the "f" object in the coverage files all look like this:

    "f": {
      "0": 0,
      "1": 0,
      "2": 0,
      "3": 0,
      "4": 0,
      "5": 0,
      "6": 0,
      "7": 0,
      "8": 0,
      "9": 0,
      "10": 0,
      "11": 0,
      "12": 0
    }

Or similar depending on the number of functions. I looked and it gets that 0 from "fn.count" in _functionsToIstanbul. The rest of my coverage looks fine, the statements, branches and lines. But functions just isn't working. I have no experience at all with how V8 coverage files work or how this package converts from V8 to Istanbul, I just know something is wrong here. 

Any idea?

**Comment by demurgos** [comment]
Hi,
Function handling is not that reliable. [In this PR](https://github.com/bcoe/c8/pull/13), some functions are completely ignored. Yesterday someone on the [Node tooling](http://devtoolscommunity.herokuapp.com/) Slack reported a similar issue where functions had a count of 0.

As mentioned [in this issue](https://github.com/istanbuljs/v8-to-istanbul/issues/6), I am working on a library update. My version seems to fix the missing functions from C8 and zero-hit count reported on Slack. The logic was changed to operate on the AST instead of using heuristics to match covered lines. You can [check it here](https://github.com/demurgos/v8-to-istanbul/tree/next) but **it is not complete**. Branch coverage is not supported yet and the API changed (especially around file loading and dealing with the CJS wrapper).
If you can post the raw V8 reports and associated source code, I could check if it works on my upcoming branch. Otherwise, I hope to finish my update by the end of August: I'll notify you when it's ready to be used.

**Comment by chriscapaci** [comment]
Thanks a lot. I'll wait for the update and see what happens then.

**Comment by demurgos** [comment]
Hi,
The plan is still to get it into `c8`.
Since my last message, I did a lot of work around `spawn-wrap`, the library used to hook into Node processes. This unfortunately turned out to be more complicated than anticipated, but at least it's done. I was then able to add a Node API (as requested in one of the other issues/PRs) and refactor `c8` to be a CLI to this API. This part is still not completely finished: I need to review how the reports are generated.

**Comment by bcoe** [comment]
I believe the issue is that if there is block coverage for a function, then there is no function coverage stanza. A potential solution would be to create a function object whenever we hit a block that has a function name associated with it.

**Comment by demurgos** [comment]
@chriscapaci Do you still encounter this issue?

**Comment by rochdev** [comment]
FWIW I'm still getting the issue on latest version.

**Comment by bcoe** [comment]
@demurgos any updates on this one?

**Comment by demurgos** [comment]
I wasn't able to reproduce it.

@rochdev could you submit some of raw V8 files that lead to a count of 0?

**Comment by rochdev** [comment]
@demurgos You can actually take a look at the repository directly: https://github.com/DataDog/dd-trace-js

It's possible I'm doing something wrong, but at a glance the rest of the coverage seems to be working.

**Comment by bcoe** [comment]
@chriscapaci still bumping into issues, there have been quite a few changes to the library since this bug was reported -- including lots of updates to V8.

**Comment by bcoe** [comment]
@chriscapaci feel free to re-open if you're still bumping into issues 👍
